"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ApiRoutes = void 0;
var express_1 = require("express");
var auth_routes_1 = require("./auth.routes");
var user_routes_1 = require("./user.routes");
var router = (0, express_1.Router)();
exports.ApiRoutes = router;
router.use("/auth", auth_routes_1.authRoutes);
router.use("/user", user_routes_1.userRoutes);
