"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.authRoutes = void 0;
var auth_controller_1 = require("controllers/auth.controller");
var express_1 = require("express");
var router = (0, express_1.Router)();
exports.authRoutes = router;
router.get("/status", auth_controller_1.authenticateUser, auth_controller_1.getLoginStatus);
router.post("/signup", auth_controller_1.signupUser);
router.post("/login", auth_controller_1.loginUser);
